name: TAIGA CI

on:
  push:
    branches: 
      - master
      - develop 
      - feature-104
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: navigate
        run: cd src
      - name: test path
        run: cd src; pwd; ls -l
      - name: compile
        run: cd src; make test
      - name: run test
        run: build/test.exe
